name: 'Wechat Work action'
description: 'message by Wechat Work, super tiny.  run one time cost 1s .support linux macos and window, base node runner not by docker'
author: 'foxundermoon'
inputs:
  url:
    description: 'web hook url'
    default: 'default value if applicable'
    required: true
  type:
    default: text
    required: false
    description: the msg type
  content:
    required: true
    description: the msg content
  at:
    description: '@ users'
    default: ''
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'green'
  icon: 'message-square'
